name: CloudFlareScan
targets:
  CloudFlareScan:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cloudflare.scan
      GENERATE_INFOPLIST_FILE: YES
